// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef MBEDTLS_CONFIG_AUTOGEN_H
#define MBEDTLS_CONFIG_AUTOGEN_H


#define MBEDTLS_ECP_MAX_BITS           256



#define MBEDTLS_MPI_MAX_SIZE    32


#define MBEDTLS_AES_C
#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_CIPHER_MODE_CFB
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_CCM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CMAC_C
#define MBEDTLS_SSL_PROTO_DTLS
#define MBEDTLS_SSL_DTLS_ANTI_REPLAY
#define MBEDTLS_SSL_DTLS_HELLO_VERIFY
#define MBEDTLS_SSL_COOKIE_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ENTROPY_RAIL_C
#define MBEDTLS_MD_C
#define MBEDTLS_ECJPAKE_C
#define MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ENTROPY_FORCE_SHA256
#define MBEDTLS_ENTROPY_MAX_SOURCES  2
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_SRV_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C


#include "config-device-acceleration.h"

/*******************************************************************************

CMAC hardware acceleration needs to be disabled to prevent the following error.

```
    In file included from /Users/matran/repos/github-silabs-openthread/examples/../src/core/crypto/pbkdf2_cmac.cpp:40:
    /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v2.7/util/third_party/mbedtls/include/mbedtls/cmac.h:223:1: error: expected '}' at end of input
    223 | }
        | ^
    In file included from /Users/matran/repos/github-silabs-openthread/examples/../src/core/crypto/pbkdf2_cmac.cpp:40:
    /Users/matran/repos/github-silabs-openthread/examples/../third_party/silabs/gecko_sdk_suite/v2.7/util/third_party/mbedtls/include/mbedtls/cmac.h:50:12: note: to match this '{'
    50 | extern "C" {
        |            ^
    make[4]: *** [crypto/libopenthread_mtd_a-pbkdf2_cmac.o] Error 1
```
There is a bug in the GSDK mbedtls `cmac.h` file where the closing bracket for the `extern "C" {` statement is nested inside `#if !defined(MBEDTLS_CMAC_ALT)`.

In other words, defining `MBEDTLS_CMAC_ALT` will cause the `extern "C" {` to never have it's scope closed, which causes the error above.

NOTE: This workaround won't be needed once the switch to GSDK v3.0 has been made
*******************************************************************************/
#undef MBEDTLS_CMAC_ALT


#include "sl_malloc.h"

#define MBEDTLS_PLATFORM_FREE_MACRO    sl_free
#define MBEDTLS_PLATFORM_CALLOC_MACRO  sl_calloc
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_C

#endif
